# BarrierLayer Configuration
# This file is automatically generated by 'make config'. Do not edit manually.

# Default launch method (proton, wine, auto)
DEFAULT_LAUNCHER = wine

# Build Mode
BUILD_MODE = debug

# Build Features
BUILD_KERNEL = N
BUILD_GUI = N
ENABLE_ULTRA_LOGGING = Y

# Compatibility
USE_WINE = 1
USE_PROTON = 0

# FPS Overlay
ENABLE_FPS_OVERLAY = no

# Optimizations
ENABLE_LTO = N
ENABLE_NATIVE = N

# Compiler (not configurable via CLI for now)
CC = gcc
AS = nasm

# Kernel build directory (not configurable via CLI for now)
KDIR ?= /lib/modules/$(shell uname -r)/build