/* BarrierLayer Configuration Header */
/* Generated by configure.sh on Thu Aug  7 20:35:14 UTC 2025 */

#ifndef BARRIERLAYER_CONFIG_H
#define BARRIERLAYER_CONFIG_H

/* System Information */
#define BARRIERLAYER_DISTRO "debian"
#define BARRIERLAYER_DISTRO_VERSION "12"
#define BARRIERLAYER_ARCH "x86_64"
#define BARRIERLAYER_KERNEL_VERSION "6.8.0-1025-gke"

/* Wine Configuration */
#define USE_WINE 0
#define WINE_BINARY ""
#define WINE_PREFIX ""
#define WINE_ARCH "win64"

/* Proton Configuration */
#define USE_PROTON 0
#define PROTON_PATH ""
#define PROTON_VERSION ""
#define USE_DXVK 1
#define USE_VKD3D 1
#define USE_ESYNC 1
#define USE_FSYNC 1

/* Anti-Cheat Configuration */
#define ENABLE_EAC 1
#define ENABLE_BATTLEYE 1
#define ENABLE_VANGUARD 1
#define ENABLE_DEBUGGER_DETECTION 1
#define ENABLE_MEMORY_PROTECTION 1
#define ENABLE_PROCESS_MASKING 1

/* Build Configuration */
#define BUILD_MODE "release"
#define BUILD_KERNEL 1
#define BUILD_GUI 1

/* Logging Configuration */
#define LOG_LEVEL 2
#define ENABLE_ULTRA_LOGGING 1
#define ENABLE_STACK_TRACES 1
#define ENABLE_FILE_LOGGING 1
#define LOG_DIRECTORY "/tmp"
#define MAX_LOG_SIZE 100

/* Stealth Configuration */
#define REMOVE_LD_PRELOAD 1
#define ENABLE_UNLINKING 1
#define BLOCK_SENSITIVE_FILES 1
#define RANDOMIZE_PROCESS_NAMES 0
#define ENABLE_CODE_INJECTION 0

/* Interface Configuration */
#define ENABLE_GUI 1
#define GUI_TOOLKIT "gtk3"
#define ENABLE_CLI 1
#define ENABLE_TRAY 0

#endif /* BARRIERLAYER_CONFIG_H */
