name: Build and Test BarrierLayer

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc nasm libseccomp-dev libgtk-3-dev linux-headers-generic

    - name: Build Project
      run: make

    - name: Run Tests
      run: make test
